### PR TITLE
add auto generator

### PR DESCRIPTION
**Pull request by Gummibeer**
**replaces:** #25 
**depends on:** #28 

```
Generating package code...
Load file...
Parse response...
deprecated constants: 0
deprecated methods: 0
Generate class...
Done!
```

With this generator a simple update to `v12.0` (current) and `v13.0` (2020) would be possible. The generator is written to generate the same constants and methods like before. So it won't have any BC. The update to v12 should follow in another PR because it will have BC. (emoji names have changed)
The generator creates also a deprecation notice (markdown) with all methods/constants dropped during an update which can be copy pasted into the PR, Changelog and so on. It generates a lot of debug files into `tmp` folder - I can drop them but it makes it easier to follow what happened during an update.

### CODE REVIEW

**Comment by freekmurze** [comment]
Pretty neat, thanks!

Could you give some ❤️to `GenerateCommand`. You could organise the code in some functions there so it's easier to get an highlevel overview to what that class does.

**Comment by Gummibeer** [comment]
@freekmurze done :)

The failing tests would be fine if #28 is merged.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
Could you add instruction to the readme on the `generator` branch on how to actually start the generator?

**Pull request merged**
