### PR TITLE
Update emoji to 15.1

### PR DESCRIPTION
**Pull request by mallardduck**
Per title, this PR will update emoji from 15.0 to 15.1.

P.s. I had a tough time getting things to actually regenerate on PHP 8.x so had to revert my PHP version to 7.4 and drop symfony/console to `5.4` instead of using `6.x`. I did all those things and am submitting this PR so as to update the Emoji without touching BC breaking stuff. But plan to follow this up with a PR that will fix the generator script and bump PHP version to drop EOL PHPs.

### CODE REVIEW

**Comment by mallardduck** [comment]
Hmm. Kinda expected that - tests might fail due to the same composer dependency issues I had. Might be able to make these happy by adding `--no-dev` or the ignore platform flag. However I also submitted the PR to drop EOL php versions too.

Initially I was thinking it'd be cool to do 2 releases; one for everyone getting emoji 15.1, then one that drops EOL php versions. But that might be too much headache for minimal benefits, so maybe drop EOL first then Emoji 15.1 bump?

**Comment by freekmurze** [comment]
>  so maybe drop EOL first then Emoji 15.1 bump?

I would be ok with that! 👍

**Comment by freekmurze** [comment]
Do rebase with main to get rid of the EOL PHP versions.

**Comment by mallardduck** [comment]
> Do rebase with main to get rid of the EOL PHP versions.

Rock on - just noticed the notifications and got that done now.

**Comment by freekmurze** [comment]
Thanks!

**Comment by mallardduck** [comment]
> Thanks!

NP...but don't thank me too soon. I just now noticed that we have an unexpected change...investigating.
Seems like something changed in the Emoji spec file we pull from.

**Comment by mallardduck** [comment]
Found it, so it seems `15.1` emoji changes the spelling of "Turkey" to the native "Türkiye".
The spelling change is totally fine and a valid change, however the rendered difference is:

Before:
```
 * @method static string flagsForFlagTurkey()
```
After:
```
 * @method static string flagsForFlagTRkiye()
```

When we want:
```
 * @method static string flagsForFlagTurkiye()
```

Fixed by: https://github.com/spatie/emoji/pull/60

**Pull request merged**
