### PR TITLE
Fix generate command to create all() static method

### PR DESCRIPTION
**Pull request by umutphp**
`composer generate` command was not creating the `all()` static method. This PR fixes it :).

### CODE REVIEW

**Comment by freekmurze** [comment]
Where is this function being called?

**Comment by umutphp** [comment]
Hi @freekmurze,

The function is added by @wijourdil with the [commit](https://github.com/spatie/emoji/commit/8af737256d9e3722c9c72e145a4cb5d4a8cd5cfc) on May 7. But, It is forgotten to add this function to the Twig file. When you run `composer generate`, the latest emoji list fetched and the class file is generated accordingly by using the Twig file. 

PS: I am using this function (Emoji::all()) to get the list of all emojis on one of my projects.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
